<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dashboard</name>
   <tag></tag>
   <elementGuidId>90e71061-71d5-4782-9bbd-258fec37fac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-page=&quot;dashboard&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-page = 'dashboard']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Dashboard' or . = ' Dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fe87008-2f9f-4eb0-9e89-1204f1be6b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-btn</value>
      <webElementGuid>3e5108f3-d9fd-44b6-8584-a6baabc1ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>7c6d31d5-2e64-478c-b2c1-42791839117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dashboard</value>
      <webElementGuid>947bdf51-3b0e-4968-8c04-415f4f114b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-78ac11c66e02d9d6185b58add063595c</value>
      <webElementGuid>cfe6ff65-b673-45ed-8c36-73e907ebfa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-page = 'dashboard']</value>
      <webElementGuid>f1c06e6f-7a21-4645-9efa-6b1a5c05c58a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-page = 'dashboard']</value>
      <webElementGuid>8142382a-6579-41f7-b7ac-0a1cc5fb61be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Dashboard' or . = ' Dashboard')]</value>
      <webElementGuid>bddb49d3-269f-4480-a42c-15cb4a09a64d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
