<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selecionar</name>
   <tag></tag>
   <elementGuidId>7d375795-58ca-4d7c-a6c5-5884854217e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.id-result-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' id-result-select ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Selecionar' or . = 'Selecionar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Selecionar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43381391-8d92-40e0-af5b-952719ec1cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75febe83-68bd-4045-8d20-17dfa4c0e429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>id-result-select</value>
      <webElementGuid>6630ffb3-0ff4-4067-b240-86ee1e3858f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecionar</value>
      <webElementGuid>0dbd3606-d225-4256-a7bf-fa4826aa50d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d1820e3839adca36eb6a5480a2fb8aaa</value>
      <webElementGuid>119f7e04-03b5-4041-a817-202157429789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' id-result-select ')]</value>
      <webElementGuid>7b2b5740-4cc9-4d7a-bd93-a300c19d8fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' id-result-select ')]</value>
      <webElementGuid>2d8fa81f-612f-4003-9193-ad43693ecfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Selecionar' or . = 'Selecionar')]</value>
      <webElementGuid>c7574316-16b8-43f0-a6c8-bd8394c8f677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' id-result-item ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' id-result-select ')]</value>
      <webElementGuid>d671e828-e715-4806-aaf6-341711bdd109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
