<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sair</name>
   <tag></tag>
   <elementGuidId>1f084689-a953-4dbf-b403-c5e148540cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-sair-tenant ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn-sair-tenant</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Sair&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6defd056-0c19-4657-91be-053e9f95d487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sair-tenant</value>
      <webElementGuid>26484fa9-4bf7-47dd-b982-adee0718caff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>logoutTenant()</value>
      <webElementGuid>da922082-718a-4ae2-be95-9841a1f48889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
             Sair
          </value>
      <webElementGuid>420179f6-c1a4-4bdf-928b-d30e6f0dcf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8687a876807a9c725fdcb05756e46c42</value>
      <webElementGuid>3d9ae08e-3e46-4107-b587-3fe932aefd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-sair-tenant ')]</value>
      <webElementGuid>4ec3512c-9540-4577-9274-ee0c426bc5ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-sair-tenant ')]</value>
      <webElementGuid>2965adbd-01c6-41eb-925e-10ce9753cc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
             Sair
          ' or . = '
             Sair
          ')]</value>
      <webElementGuid>5d2bf9cf-6e6d-47b5-86a7-375bab6acb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
