<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn-sair</name>
   <tag></tag>
   <elementGuidId>c28cb5d6-bc1e-4539-a596-ef096c374655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-sair</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn-sair']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Sair&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15e2b752-6fe5-4a85-8fdf-07aa9a77bd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sair</value>
      <webElementGuid>176f2dfb-eb15-4109-90b3-bbd3e127e9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-sair</value>
      <webElementGuid>d929bc08-16fd-4f56-9c0a-f6fe2dec65f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sair</value>
      <webElementGuid>1a83940d-3d56-4f6f-90b7-02659ec5b262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b3a3299cdecf858a482762637fabcbdf</value>
      <webElementGuid>9caec373-f7d7-496a-a46b-a9a076245040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn-sair']</value>
      <webElementGuid>3a05c1f1-b341-4f3f-8900-e95187ae0ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn-sair']</value>
      <webElementGuid>9172b939-ab4e-40de-a457-1e2ea982b080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-sair' and (text() = ' Sair' or . = ' Sair')]</value>
      <webElementGuid>e27c9078-435d-4a6e-b1dd-321a0cb7e1a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
