<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_22</name>
   <tag></tag>
   <elementGuidId>af13fdf4-e71f-46b2-bda1-83af8782b6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.has-appointment:nth-child(23)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 23)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '22' or . = '22')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;22&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7efebe1-f263-4cae-8483-63e27a7f1b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day has-appointment</value>
      <webElementGuid>c1d5264f-a539-4c59-a601-34e4c0d2c49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>58e9019e-d645-4eb8-9a77-9422a97b005e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f2e6cf9631e42af031ba8fb3b2a1a3a</value>
      <webElementGuid>d89435c0-91f2-471a-ba88-fb616cec8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 23)]</value>
      <webElementGuid>4aecab28-2e6e-40c7-8c77-b73b6bf5c209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 23)]</value>
      <webElementGuid>cf2976a0-22bf-4f63-b2a3-3173c360c475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '22' or . = '22')]</value>
      <webElementGuid>238a35b4-74d5-4991-ab1b-a94c41d42c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' calendar-day ') and (name() = 'button') and (position() = 23)]</value>
      <webElementGuid>384c74b7-c746-4eaf-9ad7-fb7590592eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
