<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_17</name>
   <tag></tag>
   <elementGuidId>938cb1f0-b393-41e8-82b4-f50997871918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 18)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.has-appointment:nth-child(18)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;17&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f63b737-571e-498a-8ce3-6eb63360b9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day has-appointment</value>
      <webElementGuid>739f88b6-85b9-418f-9753-530cc3ed6f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>c234daa3-44aa-489a-bbe4-562ca60cb8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-56e181bded2a8fa664c1940665557284</value>
      <webElementGuid>585be693-0a80-425c-b8b8-b59c8533d39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 18)]</value>
      <webElementGuid>7e3f31b6-57bd-47f2-a477-239a8cce1e2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' has-appointment ') and (position() = 18)]</value>
      <webElementGuid>4c750406-f7a5-4d59-a97b-c155c4aeb09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '17' or . = '17')]</value>
      <webElementGuid>617f4a6a-0697-4b00-a857-01e7e276b438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
