<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tip-confirm</name>
   <tag></tag>
   <elementGuidId>846e5f69-64e4-4bba-b71b-76d8f7eadf84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tip-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'tip-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Adicionar caixinha&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6aee4d0-b07f-4551-8e46-96bcaf1f9d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7de837d6-03ac-4770-944e-0447c2741ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tip-btn-confirm</value>
      <webElementGuid>6fda1e2e-4760-489b-b171-b4dafe309f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tip-confirm</value>
      <webElementGuid>eadf0458-e6dc-4cfa-8e7e-4a6cd6ecd80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Adicionar caixinha</value>
      <webElementGuid>13d8f95c-8bb6-4578-8b26-97cb591d3c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f4d442696de2042916b013229a744d12</value>
      <webElementGuid>1fff501f-e33d-484f-883f-78de1e286b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'tip-confirm']</value>
      <webElementGuid>b11cd8d0-705a-40a4-b227-4059f912f22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'tip-confirm']</value>
      <webElementGuid>fb70f0e9-5439-4f74-bdb3-2ade7648c96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'tip-confirm' and (text() = ' Adicionar caixinha' or . = ' Adicionar caixinha')]</value>
      <webElementGuid>ba4e14e0-2a3d-4f55-986e-7f084844818f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
