<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pag-tip-btn</name>
   <tag></tag>
   <elementGuidId>3e1aea39-d08b-4657-ad09-26cc694cefed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pag-tip-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'pag-tip-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Adicionar caixinha ›&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aead33d-1a36-46ae-aef0-3d237fffb69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f3c2fec-d0e9-4f08-bba0-8cf941a36694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pag-tip-btn</value>
      <webElementGuid>63d43172-80a5-4aa8-934b-89255cd6e1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pag-tip-btn</value>
      <webElementGuid>8ffeedfe-b495-48e0-a45a-89e5de5fbcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Adicionar caixinha</value>
      <webElementGuid>dacb3012-9499-4d4f-bb7b-c7fb38d81824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d976222b8ea3a4e274893c4bd2ee27f9</value>
      <webElementGuid>c34d5fbf-086d-4481-8e5e-ec4ed3bc3d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'pag-tip-btn']</value>
      <webElementGuid>1e1b12b3-9c90-422f-8e16-f06d4b1ed9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'pag-tip-btn']</value>
      <webElementGuid>0b874630-6711-48ca-930b-79c106ef7fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pag-tip-btn' and (text() = ' Adicionar caixinha' or . = ' Adicionar caixinha')]</value>
      <webElementGuid>5df3a49e-a020-4bcf-a39e-63d0219fb207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
