<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_R 10,00</name>
   <tag></tag>
   <elementGuidId>72233f3e-3ae8-445e-8425-7757ff2e11d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.tip-preset:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tip-preset ') and (position() = 3)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;R$ 10,00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df828365-3b50-48b3-a805-2b216d4aad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42879759-26bd-41d9-86c5-dc11f2f61d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tip-preset</value>
      <webElementGuid>88beae08-7080-41ea-b844-7e54a3a36f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3042ed15-b0d0-48dd-9d51-a0f6598638b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R$ 10,00</value>
      <webElementGuid>e312344f-23ff-4ca2-a0fb-e723b373ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3f6169755ef743f16263045d8c0c4c14</value>
      <webElementGuid>3c37f41b-d69d-46c6-8d06-b75a2f3fad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tip-preset ') and (position() = 3)]</value>
      <webElementGuid>907385ef-a25a-4ee2-9942-6c07999a70ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tip-preset ') and (position() = 3)]</value>
      <webElementGuid>bf0c969a-7652-4a61-a8c2-2b1e84fc05a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'R$ 10,00' or . = 'R$ 10,00')]</value>
      <webElementGuid>a8503bc6-b7d9-44e5-a3be-f4f2d1779ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
