<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nome</name>
   <tag></tag>
   <elementGuidId>d122b195-5638-42d5-acad-f9a0c1445b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-search-type=&quot;nome&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-search-type = 'nome']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = '
           Nome
        ' or . = '
           Nome
        ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot; Nome&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>abdd721c-63a7-45a4-9a45-1e5c9b8563de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70a8a2ec-f5eb-4870-9450-65fd3a13113f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>id-search-tab</value>
      <webElementGuid>a4e3f31a-4859-4da4-ae50-169cb2ec06d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-type</name>
      <type>Main</type>
      <value>nome</value>
      <webElementGuid>a42e748a-9cdd-441f-b4da-a40c024166db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>aab083ad-13a7-4600-ae25-8e4443f410f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c84b14d3-91cd-4176-ba1b-4870026a53ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
           Nome
        </value>
      <webElementGuid>8a817e3f-0ef7-4621-ba65-2bb3abd07c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-01770c16df823a4255c57c5f71e5a090</value>
      <webElementGuid>ecb093cf-f69b-470d-95a7-d404218ed573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-search-type = 'nome']</value>
      <webElementGuid>83d8459a-e49f-4357-8025-a7997ffa0a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-search-type = 'nome']</value>
      <webElementGuid>7f2156b4-7c63-4eb5-ab39-1d523009a7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
           Nome
        ' or . = '
           Nome
        ')]</value>
      <webElementGuid>631453d1-5b27-4c65-8005-09463466229e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
