<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aplicar</name>
   <tag></tag>
   <elementGuidId>58343682-1f71-4965-bb18-572e27a2918d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-dash-apply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-dash-apply ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Aplicar' or . = 'Aplicar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Aplicar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ab38014-4bcb-4185-8f8d-2daca6122f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-submit btn-dash-apply</value>
      <webElementGuid>d8b877cb-fba6-4690-a9d1-fa208589f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>aplicarFiltrosDashboard()</value>
      <webElementGuid>f9678ad4-80da-4e0c-9423-cbbff8704a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplicar</value>
      <webElementGuid>5a92d815-d7e9-4ae7-9ec0-b692583ceff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f87857c063a0f2abcfa20b8bb831bd9b</value>
      <webElementGuid>4ed403dd-ff88-4c70-8759-80fa97b866ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-dash-apply ')]</value>
      <webElementGuid>2ec1dccb-07bf-43b2-896e-fc34e88f925b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-dash-apply ')]</value>
      <webElementGuid>0e1a011f-cab6-4cf4-9042-71e8a16d6a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Aplicar' or . = 'Aplicar')]</value>
      <webElementGuid>ff1b1c11-2bcf-4a31-9611-32c7884bf536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
