<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_btn-novo-agendamento</name>
   <tag></tag>
   <elementGuidId>9c3c5188-227a-45ce-8dc8-8c5e900c42c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-novo-agendamento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'btn-novo-agendamento']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btn-novo-agendamento' and (text() = ' Novo' or . = ' Novo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;+ Novo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>118d4dd4-3530-47ea-be36-0f8d0a03aac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-novo</value>
      <webElementGuid>c3bd9fca-abe9-4cb2-8c03-a08e086f65d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-novo-agendamento</value>
      <webElementGuid>1370b772-b2e6-4783-877c-0f2acab18c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Novo</value>
      <webElementGuid>c0aa14fe-4c80-40ab-ad20-8a0f754dbd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd99e473ad044d3d779dd3df2696f355</value>
      <webElementGuid>71eb9d06-29aa-4ff5-bca8-64546b32f112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'btn-novo-agendamento']</value>
      <webElementGuid>f35d4859-83fa-40f5-8b42-03a3d5dd33cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'btn-novo-agendamento']</value>
      <webElementGuid>277cc765-85f7-4cf3-b5f8-da1af5adcc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-novo-agendamento' and (text() = ' Novo' or . = ' Novo')]</value>
      <webElementGuid>fad6c369-c97b-4b71-98f2-2125735f3bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
