<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Clientes</name>
   <tag></tag>
   <elementGuidId>789626db-d528-4875-9310-0b713be60377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-page=&quot;clientes&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-page = 'clientes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Clientes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a7cfd1b-0e9c-4d8f-b544-4c96b79bd7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-btn</value>
      <webElementGuid>ae76fd2e-ad5f-44d6-9c02-71d6aeea2f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>clientes</value>
      <webElementGuid>ce4a29c8-aac2-4d2c-9823-add1c0209b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clientes</value>
      <webElementGuid>1f5329cb-5ccb-491c-8993-87f1f9f8237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e7ec73452ee42b4879627ab0f27aa625</value>
      <webElementGuid>9fbd4dce-6f94-4420-8b01-a1efac9936be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-page = 'clientes']</value>
      <webElementGuid>15cb5ce3-d904-450c-988d-b8abc2836fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-page = 'clientes']</value>
      <webElementGuid>4830d2ea-5e29-4216-9a82-cd60423ac143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Clientes' or . = ' Clientes')]</value>
      <webElementGuid>1bdd1399-7838-4fb2-a1e4-d5a1495064dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
