<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Daryl</name>
   <tag></tag>
   <elementGuidId>002c7d15-4677-4532-b466-cb8ab624cda5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-value=&quot;Daryl&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-value = 'Daryl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Daryl' or . = 'Daryl')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Daryl$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b49f45f7-8f96-454d-8013-313e17249268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svc-prof-option</value>
      <webElementGuid>b83560ec-9153-485b-8683-0f6835ab9e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Daryl</value>
      <webElementGuid>a900c113-91cc-419a-a91a-435daf1be1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daryl</value>
      <webElementGuid>2e51c7da-f55d-45d4-aee2-3bcdba3d1118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-268ab5a1d7966fe7e453a95f7333d63f</value>
      <webElementGuid>aa86b8bd-7b7c-4df2-a475-b0b3194035d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-value = 'Daryl']</value>
      <webElementGuid>e59e1efc-bef6-4635-89c6-257f17ae28e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-value = 'Daryl']</value>
      <webElementGuid>38340e79-e63a-4661-8fda-d0cd965c5782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Daryl' or . = 'Daryl')]</value>
      <webElementGuid>f686e2ab-9d70-4f8a-a716-78d7be3cbbc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
