<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dash-faturamento</name>
   <tag></tag>
   <elementGuidId>c4370968-4400-43a0-ba06-b8531c12426c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dash-faturamento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'dash-faturamento']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'dash-faturamento' and (text() = 'R$ 0,00' or . = 'R$ 0,00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dash-faturamento</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>adf7184c-213b-4b6c-9622-2e25ef3fcb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dash-card-value</value>
      <webElementGuid>81a006f6-3e71-41b1-bf7d-a31b57404def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dash-faturamento</value>
      <webElementGuid>94924d75-1b97-499b-abb3-770a1be08af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-desc-sum</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ca31e15-1704-467c-8b93-308dbaf1ec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prod-sum</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef16cc63-2f15-4ad9-b9c3-7500d0d3b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip-sum</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d93b6f7-5af9-4b5f-873f-9f531aff1d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-base-fat</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80e24923-d5b9-4441-86ad-87d3d2b9a01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R$ 0,00</value>
      <webElementGuid>c9b402f0-d3f0-4b4c-aabc-58c0e4d06fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-57b772f237e27d8fd76fdd8594dbbe6a</value>
      <webElementGuid>e969b892-06ac-4651-8ff8-40ad4de4a429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'dash-faturamento']</value>
      <webElementGuid>218ca48b-81fa-43ba-98b0-c0d609885e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'dash-faturamento']</value>
      <webElementGuid>405da01a-d04e-4431-8efb-42a5854dea00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dash-faturamento' and (text() = 'R$ 0,00' or . = 'R$ 0,00')]</value>
      <webElementGuid>838c0021-5257-4cd3-8688-54665dfcef9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
