<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selecione</name>
   <tag></tag>
   <elementGuidId>86ecb05c-7a23-4949-9311-5d9d781cb1e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.svc-prof-trigger-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' svc-prof-trigger-content ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Selecione...' or . = 'Selecione...')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Selecione\.\.\.$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d6b7093-0adb-498e-bb4d-342da5987b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svc-prof-trigger-content</value>
      <webElementGuid>9c5b72ca-abed-4e17-9bff-48e0477fb8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleProfDropdown(this)</value>
      <webElementGuid>89f24fcc-3720-4d2b-a971-b86bf1825056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecione...</value>
      <webElementGuid>b8570e46-765e-4a79-bc52-6ddfc637399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-451ba232ab3ef2f7d5dde3e9e7a601ea</value>
      <webElementGuid>d2cdf3fe-bf10-41d2-a4d3-d62e329b36e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' svc-prof-trigger-content ')]</value>
      <webElementGuid>5c6028fa-b56c-495a-a771-c4d08ced5137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' svc-prof-trigger-content ')]</value>
      <webElementGuid>6ed237ab-312e-496e-a88a-06bb631d0f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selecione...' or . = 'Selecione...')]</value>
      <webElementGuid>b64a5147-34b8-4c90-95e7-4e82f00973c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' svc-prof-trigger ')]</value>
      <webElementGuid>d30236f2-c17b-4049-a356-9e1b639c039f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
