<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dash-total-ag</name>
   <tag></tag>
   <elementGuidId>9ad7ca2c-9ae4-48d0-a1b4-c49ca1d8ceb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dash-total-ag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'dash-total-ag']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'dash-total-ag' and (text() = '34' or . = '34')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dash-total-ag</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fd7d8df-34f5-42e0-b579-cc931a75fe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dash-card-value</value>
      <webElementGuid>a6a6cb78-4978-4882-af16-f13b548d3fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dash-total-ag</value>
      <webElementGuid>8f16819e-d05f-4e60-a850-1a2f727b2142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>f1271e1f-bd21-4fd5-bb85-3e975d984761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-298ba60b5d457b2969ee3ace8abf07be</value>
      <webElementGuid>519e8973-04b6-40c8-9047-ad804bfbc79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'dash-total-ag']</value>
      <webElementGuid>b8d91c5b-65ab-4be9-b595-b86b2e880d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'dash-total-ag']</value>
      <webElementGuid>dfb43b79-129c-45f5-8122-5ad94f242177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dash-total-ag' and (text() = '34' or . = '34')]</value>
      <webElementGuid>b7b62a20-9bcc-4046-9328-1a9ce8ec3bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dash-total-ag' and (text() = '0' or . = '0')]</value>
      <webElementGuid>fc150f42-58c2-447f-9a9f-4f5ae016089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dash-total-ag' and (text() = '29' or . = '29')]</value>
      <webElementGuid>5b18bd54-e189-42ae-b1db-a08d3b284d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
