<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dash-inicio</name>
   <tag></tag>
   <elementGuidId>54d35e97-a56c-4c02-8a59-e46c13c05116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dash-inicio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'dash-inicio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'date' and @id = 'dash-inicio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dash-inicio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b111f92-5377-45e5-85d6-2fa8817cb22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>849e1b52-b3c8-4051-9499-29bae3fdb42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dash-inicio</value>
      <webElementGuid>8b63dd56-bd97-4d3e-9a6c-69c0d949ab8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bound-filtro</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4578834-6e5d-49d5-8a30-2f852467643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-51662f8c04e4d9059b89280423174c34</value>
      <webElementGuid>28b60b7e-4a02-4a1b-82aa-3e234186ec9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'dash-inicio']</value>
      <webElementGuid>87d11a4d-c021-45a4-a45f-25b7ddf895ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'dash-inicio']</value>
      <webElementGuid>abb42870-f258-44a4-858b-6f02a41952ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'dash-inicio']</value>
      <webElementGuid>2605a7df-4146-4b5d-b080-ad59e42b1959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
