<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Senha</name>
   <tag></tag>
   <elementGuidId>d76b14c1-1a2e-472b-81f8-db38969df9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-pass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'login-pass']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @id = 'login-pass' and @placeholder = 'Senha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Senha&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08f3b2b0-fa37-4d36-bc4e-3d3e07a5797d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>87423231-2675-4535-8a1a-dab8e98944f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-pass</value>
      <webElementGuid>4f8e5c16-3952-4ff0-9cfb-191375f902f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>b3dbbc42-bc52-4ab4-b17d-99ad4dfb7936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>bc96906d-d522-4049-ba63-7167301d6fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-57bcf44de27c724f20795c8ee2b28a1a</value>
      <webElementGuid>5f4b7a7c-e4ee-4dfd-aca9-eab7e9e9dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'login-pass']</value>
      <webElementGuid>30acd2fa-9343-4787-8ca0-80265940f3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'login-pass']</value>
      <webElementGuid>6a1de036-51db-4087-ba98-ac200fe789df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'login-pass' and @placeholder = 'Senha']</value>
      <webElementGuid>2dc07933-f3ea-4155-b6d4-903d4deff21c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
