<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ag-data</name>
   <tag></tag>
   <elementGuidId>3a37c04a-d5bd-49ca-8419-d184e9831d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ag-data']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'date' and @id = 'ag-data']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ag-data</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d8051c6-9d4b-48ba-b8fb-97924f1a90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d47f0b14-a975-493e-a6cb-decfd3638985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-data</value>
      <webElementGuid>a20b3da7-3a08-4ee4-b167-6b936d7e37c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-752617a5db2aa18862877289a772f15b</value>
      <webElementGuid>6152dd7b-56ee-4c24-ba60-4b11b9b622db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ag-data']</value>
      <webElementGuid>fbfce48d-f101-4944-9f35-d938d24256f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ag-data']</value>
      <webElementGuid>0276b6f9-73c0-4b0a-a772-0cc225dad811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'ag-data']</value>
      <webElementGuid>1ba7420c-8e66-4e8c-84ad-5a1e10894c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
