<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buscar cliente por nome</name>
   <tag></tag>
   <elementGuidId>115fd796-a6ac-48b1-8a2e-73c64685d223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clients-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'clients-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Buscar cliente por nome...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>552de1cf-a23b-4164-8e0e-9d4a4be936e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbdbfef4-db51-4115-a71e-f5d6e565e9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clients-search-input</value>
      <webElementGuid>b73cf58d-8bb5-4345-aa84-b39c6676d57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-bar-input</value>
      <webElementGuid>e4905dda-1125-4906-b942-b509acecf3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar cliente por nome...</value>
      <webElementGuid>01149bef-e8d6-48b0-bee0-29bbacc5b3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1158937-bcc7-4413-8c36-960f47b81480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buscar cliente por nome</value>
      <webElementGuid>1da015d7-d35b-422d-bf39-89e18a447bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f2f1f095874bd879d688143657b70dcf</value>
      <webElementGuid>8dfe224a-c994-459e-acee-867100e27112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'clients-search-input']</value>
      <webElementGuid>d97b8a39-99cb-4067-ab51-1a698d13e541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'clients-search-input']</value>
      <webElementGuid>5501834d-82e5-4493-8e77-b52cf78308b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'clients-search-input' and @placeholder = 'Buscar cliente por nome...']</value>
      <webElementGuid>2d9cf75b-8bc6-4d77-b446-09477b445d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
