<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite o nome (ex_ Maria)</name>
   <tag></tag>
   <elementGuidId>74b7d07f-508d-4831-b829-b792172a999d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-nome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id-nome']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'id-nome' and @placeholder = 'Digite o nome (ex: Maria)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite o nome (ex: Maria)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f415ba4a-38dd-49f2-8474-9798f54d2cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b3cdf47-3ae5-4fb4-93b5-42ecee0b2b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-nome</value>
      <webElementGuid>815c0af5-f08e-4dc5-ae6a-aa3d02108490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite o nome (ex: Maria)</value>
      <webElementGuid>e7818b5c-be8d-4944-84b9-412cb3205226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed1cd0d0-bb63-4b01-b598-dc66407231a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-99b04dadcd5cc34e7c80d29a31d68fc6</value>
      <webElementGuid>da613d06-0e82-4a9d-94bf-1b8142ba74b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id-nome']</value>
      <webElementGuid>b434a77e-3366-4f7f-89fe-612679c8721c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id-nome']</value>
      <webElementGuid>933e89a0-c9e4-4d74-b8a6-8130af0f2eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id-nome' and @placeholder = 'Digite o nome (ex: Maria)']</value>
      <webElementGuid>ada51cbc-1790-4240-8d1b-fa18fb50a2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
