analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3491048,"name"\:"OrangeHRM Trial \#3491048","teamId"\:3483496,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3505074,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3483496,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
